# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and tests

on:
  push:
    branches:
      - 'feature/*'
      - 'main'
  pull_request:
    branches: [ main ]

jobs:
  build:
    environment: CIRelease
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: actions/checkout@v3
      - name: Run gradle release
        env:
          JAVA_OPTS: "-Xmx1024M"
          GRADLE_OPTS: "-Dorg.gradle.daemon=true"
        run: ./gradlew -Pversion=1.0.0-SNAPSHOT test -s
